const os = require('node:os')

console.log('USER INFO: ', os.userInfo())
console.log('HOSTNAME: ', os.hostname())
console.log('HOME DIR: ', os.homedir())
console.log('PLATFORM', os.platform())
console.log('RELEASE', os.release())
console.log('VERSION: ', os.version())
console.log('ARCH: ', os.arch())
console.log('FREE MEM: ', os.freemem() / 1024 / 1024)
console.log('TOTAL MEM: ', os.totalmem() / 1024 / 1024)
console.log('CPUs: ', os.cpus())
console.log('NETWORK INTERFACES: ', os.networkInterfaces())
console.log('UPTIME: ', os.uptime() / 60 / 60)
